//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace NgoVanKhai_CNTT2K60_191200552.Models
{
    internal class RegularExpcressionAttribute : Attribute
    {
        private string v;
        private string errorMessage;

        public RegularExpcressionAttribute(string v, string ErrorMessage)
        {
            this.v = v;
            errorMessage = ErrorMessage;
        }
    }
}