//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NgoVanKhai_CNTT2K60_191200552.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.SPtheoMaus = new HashSet<SPtheoMau>();
        }
    
        public string MaSanPham { get; set; }
        //[RegularExpcression(@"[A-Z]{2}[0-9]{4}", ErrorMessage = "Name is not valid.")]
        public string TenSanPham { get; set; }
        public string MaPhanLoai { get; set; }
        //[RegularExpression(@"[A-Z]{2}[0-9]{4}", ErrorMessage = "Id is not valid.")]
        public Nullable<long> GiaNhap { get; set; }
        //[RegularExpression(@"[A-Z]{2}[0-9]{4}", ErrorMessage = "Id is not valid.")]
        public Nullable<long> DonGiaBanNhoNhat { get; set; }
        //[RegularExpression(@"[A-Z]{2}[0-9]{4}", ErrorMessage = "Id is not valid.")]
        public Nullable<long> DonGiaBanLonNhat { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string MoTaNgan { get; set; }
        public string AnhDaiDien { get; set; }
        public Nullable<bool> NoiBat { get; set; }
        public string MaPhanLoaiPhu { get; set; }
    
        public virtual PhanLoai PhanLoai { get; set; }
        public virtual PhanLoaiPhu PhanLoaiPhu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPtheoMau> SPtheoMaus { get; set; }
    }
}
