#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIN02_01.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WebBanVaLi")]
	public partial class WebBanValiDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttLoaiSP(tLoaiSP instance);
    partial void UpdatetLoaiSP(tLoaiSP instance);
    partial void DeletetLoaiSP(tLoaiSP instance);
    partial void InserttDanhMucSP(tDanhMucSP instance);
    partial void UpdatetDanhMucSP(tDanhMucSP instance);
    partial void DeletetDanhMucSP(tDanhMucSP instance);
    #endregion
		
		public WebBanValiDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["WebBanVaLiConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public WebBanValiDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WebBanValiDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WebBanValiDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WebBanValiDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tLoaiSP> tLoaiSPs
		{
			get
			{
				return this.GetTable<tLoaiSP>();
			}
		}
		
		public System.Data.Linq.Table<tDanhMucSP> tDanhMucSPs
		{
			get
			{
				return this.GetTable<tDanhMucSP>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tLoaiSP")]
	public partial class tLoaiSP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLoai;
		
		private string _Loai;
		
		private EntitySet<tDanhMucSP> _tDanhMucSPs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiChanging(string value);
    partial void OnMaLoaiChanged();
    partial void OnLoaiChanging(string value);
    partial void OnLoaiChanged();
    #endregion
		
		public tLoaiSP()
		{
			this._tDanhMucSPs = new EntitySet<tDanhMucSP>(new Action<tDanhMucSP>(this.attach_tDanhMucSPs), new Action<tDanhMucSP>(this.detach_tDanhMucSPs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoai", DbType="Char(25) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLoai
		{
			get
			{
				return this._MaLoai;
			}
			set
			{
				if ((this._MaLoai != value))
				{
					this.OnMaLoaiChanging(value);
					this.SendPropertyChanging();
					this._MaLoai = value;
					this.SendPropertyChanged("MaLoai");
					this.OnMaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loai", DbType="NVarChar(100)")]
		public string Loai
		{
			get
			{
				return this._Loai;
			}
			set
			{
				if ((this._Loai != value))
				{
					this.OnLoaiChanging(value);
					this.SendPropertyChanging();
					this._Loai = value;
					this.SendPropertyChanged("Loai");
					this.OnLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tLoaiSP_tDanhMucSP", Storage="_tDanhMucSPs", ThisKey="MaLoai", OtherKey="MaLoai")]
		public EntitySet<tDanhMucSP> tDanhMucSPs
		{
			get
			{
				return this._tDanhMucSPs;
			}
			set
			{
				this._tDanhMucSPs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tDanhMucSPs(tDanhMucSP entity)
		{
			this.SendPropertyChanging();
			entity.tLoaiSP = this;
		}
		
		private void detach_tDanhMucSPs(tDanhMucSP entity)
		{
			this.SendPropertyChanging();
			entity.tLoaiSP = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tDanhMucSP")]
	public partial class tDanhMucSP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSP;
		
		private string _TenSP;
		
		private string _MaChatLieu;
		
		private string _NganLapTop;
		
		private string _Model;
		
		private string _MauSac;
		
		private string _MaKichThuoc;
		
		private System.Nullable<double> _CanNang;
		
		private System.Nullable<double> _DoNoi;
		
		private string _MaHangSX;
		
		private string _MaNuocSX;
		
		private string _MaDacTinh;
		
		private string _Website;
		
		private System.Nullable<double> _ThoiGianBaoHanh;
		
		private string _GioiThieuSP;
		
		private System.Nullable<double> _Gia;
		
		private System.Nullable<double> _ChietKhau;
		
		private string _MaLoai;
		
		private string _MaDT;
		
		private string _Anh;
		
		private EntityRef<tLoaiSP> _tLoaiSP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSPChanging(string value);
    partial void OnMaSPChanged();
    partial void OnTenSPChanging(string value);
    partial void OnTenSPChanged();
    partial void OnMaChatLieuChanging(string value);
    partial void OnMaChatLieuChanged();
    partial void OnNganLapTopChanging(string value);
    partial void OnNganLapTopChanged();
    partial void OnModelChanging(string value);
    partial void OnModelChanged();
    partial void OnMauSacChanging(string value);
    partial void OnMauSacChanged();
    partial void OnMaKichThuocChanging(string value);
    partial void OnMaKichThuocChanged();
    partial void OnCanNangChanging(System.Nullable<double> value);
    partial void OnCanNangChanged();
    partial void OnDoNoiChanging(System.Nullable<double> value);
    partial void OnDoNoiChanged();
    partial void OnMaHangSXChanging(string value);
    partial void OnMaHangSXChanged();
    partial void OnMaNuocSXChanging(string value);
    partial void OnMaNuocSXChanged();
    partial void OnMaDacTinhChanging(string value);
    partial void OnMaDacTinhChanged();
    partial void OnWebsiteChanging(string value);
    partial void OnWebsiteChanged();
    partial void OnThoiGianBaoHanhChanging(System.Nullable<double> value);
    partial void OnThoiGianBaoHanhChanged();
    partial void OnGioiThieuSPChanging(string value);
    partial void OnGioiThieuSPChanged();
    partial void OnGiaChanging(System.Nullable<double> value);
    partial void OnGiaChanged();
    partial void OnChietKhauChanging(System.Nullable<double> value);
    partial void OnChietKhauChanged();
    partial void OnMaLoaiChanging(string value);
    partial void OnMaLoaiChanged();
    partial void OnMaDTChanging(string value);
    partial void OnMaDTChanged();
    partial void OnAnhChanging(string value);
    partial void OnAnhChanged();
    #endregion
		
		public tDanhMucSP()
		{
			this._tLoaiSP = default(EntityRef<tLoaiSP>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSP", DbType="Char(25) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSP
		{
			get
			{
				return this._MaSP;
			}
			set
			{
				if ((this._MaSP != value))
				{
					this.OnMaSPChanging(value);
					this.SendPropertyChanging();
					this._MaSP = value;
					this.SendPropertyChanged("MaSP");
					this.OnMaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSP", DbType="NVarChar(150)")]
		public string TenSP
		{
			get
			{
				return this._TenSP;
			}
			set
			{
				if ((this._TenSP != value))
				{
					this.OnTenSPChanging(value);
					this.SendPropertyChanging();
					this._TenSP = value;
					this.SendPropertyChanged("TenSP");
					this.OnTenSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChatLieu", DbType="Char(25)")]
		public string MaChatLieu
		{
			get
			{
				return this._MaChatLieu;
			}
			set
			{
				if ((this._MaChatLieu != value))
				{
					this.OnMaChatLieuChanging(value);
					this.SendPropertyChanging();
					this._MaChatLieu = value;
					this.SendPropertyChanged("MaChatLieu");
					this.OnMaChatLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NganLapTop", DbType="NVarChar(55)")]
		public string NganLapTop
		{
			get
			{
				return this._NganLapTop;
			}
			set
			{
				if ((this._NganLapTop != value))
				{
					this.OnNganLapTopChanging(value);
					this.SendPropertyChanging();
					this._NganLapTop = value;
					this.SendPropertyChanged("NganLapTop");
					this.OnNganLapTopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Model", DbType="NVarChar(55)")]
		public string Model
		{
			get
			{
				return this._Model;
			}
			set
			{
				if ((this._Model != value))
				{
					this.OnModelChanging(value);
					this.SendPropertyChanging();
					this._Model = value;
					this.SendPropertyChanged("Model");
					this.OnModelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MauSac", DbType="NVarChar(55)")]
		public string MauSac
		{
			get
			{
				return this._MauSac;
			}
			set
			{
				if ((this._MauSac != value))
				{
					this.OnMauSacChanging(value);
					this.SendPropertyChanging();
					this._MauSac = value;
					this.SendPropertyChanged("MauSac");
					this.OnMauSacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKichThuoc", DbType="Char(25)")]
		public string MaKichThuoc
		{
			get
			{
				return this._MaKichThuoc;
			}
			set
			{
				if ((this._MaKichThuoc != value))
				{
					this.OnMaKichThuocChanging(value);
					this.SendPropertyChanging();
					this._MaKichThuoc = value;
					this.SendPropertyChanged("MaKichThuoc");
					this.OnMaKichThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CanNang", DbType="Float")]
		public System.Nullable<double> CanNang
		{
			get
			{
				return this._CanNang;
			}
			set
			{
				if ((this._CanNang != value))
				{
					this.OnCanNangChanging(value);
					this.SendPropertyChanging();
					this._CanNang = value;
					this.SendPropertyChanged("CanNang");
					this.OnCanNangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoNoi", DbType="Float")]
		public System.Nullable<double> DoNoi
		{
			get
			{
				return this._DoNoi;
			}
			set
			{
				if ((this._DoNoi != value))
				{
					this.OnDoNoiChanging(value);
					this.SendPropertyChanging();
					this._DoNoi = value;
					this.SendPropertyChanged("DoNoi");
					this.OnDoNoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHangSX", DbType="Char(25)")]
		public string MaHangSX
		{
			get
			{
				return this._MaHangSX;
			}
			set
			{
				if ((this._MaHangSX != value))
				{
					this.OnMaHangSXChanging(value);
					this.SendPropertyChanging();
					this._MaHangSX = value;
					this.SendPropertyChanged("MaHangSX");
					this.OnMaHangSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNuocSX", DbType="Char(25)")]
		public string MaNuocSX
		{
			get
			{
				return this._MaNuocSX;
			}
			set
			{
				if ((this._MaNuocSX != value))
				{
					this.OnMaNuocSXChanging(value);
					this.SendPropertyChanging();
					this._MaNuocSX = value;
					this.SendPropertyChanged("MaNuocSX");
					this.OnMaNuocSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDacTinh", DbType="Char(25)")]
		public string MaDacTinh
		{
			get
			{
				return this._MaDacTinh;
			}
			set
			{
				if ((this._MaDacTinh != value))
				{
					this.OnMaDacTinhChanging(value);
					this.SendPropertyChanging();
					this._MaDacTinh = value;
					this.SendPropertyChanged("MaDacTinh");
					this.OnMaDacTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Website", DbType="Char(155)")]
		public string Website
		{
			get
			{
				return this._Website;
			}
			set
			{
				if ((this._Website != value))
				{
					this.OnWebsiteChanging(value);
					this.SendPropertyChanging();
					this._Website = value;
					this.SendPropertyChanged("Website");
					this.OnWebsiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianBaoHanh", DbType="Float")]
		public System.Nullable<double> ThoiGianBaoHanh
		{
			get
			{
				return this._ThoiGianBaoHanh;
			}
			set
			{
				if ((this._ThoiGianBaoHanh != value))
				{
					this.OnThoiGianBaoHanhChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianBaoHanh = value;
					this.SendPropertyChanged("ThoiGianBaoHanh");
					this.OnThoiGianBaoHanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiThieuSP", DbType="NVarChar(255)")]
		public string GioiThieuSP
		{
			get
			{
				return this._GioiThieuSP;
			}
			set
			{
				if ((this._GioiThieuSP != value))
				{
					this.OnGioiThieuSPChanging(value);
					this.SendPropertyChanging();
					this._GioiThieuSP = value;
					this.SendPropertyChanged("GioiThieuSP");
					this.OnGioiThieuSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Float")]
		public System.Nullable<double> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChietKhau", DbType="Float")]
		public System.Nullable<double> ChietKhau
		{
			get
			{
				return this._ChietKhau;
			}
			set
			{
				if ((this._ChietKhau != value))
				{
					this.OnChietKhauChanging(value);
					this.SendPropertyChanging();
					this._ChietKhau = value;
					this.SendPropertyChanged("ChietKhau");
					this.OnChietKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoai", DbType="Char(25)")]
		public string MaLoai
		{
			get
			{
				return this._MaLoai;
			}
			set
			{
				if ((this._MaLoai != value))
				{
					if (this._tLoaiSP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiChanging(value);
					this.SendPropertyChanging();
					this._MaLoai = value;
					this.SendPropertyChanged("MaLoai");
					this.OnMaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDT", DbType="Char(25)")]
		public string MaDT
		{
			get
			{
				return this._MaDT;
			}
			set
			{
				if ((this._MaDT != value))
				{
					this.OnMaDTChanging(value);
					this.SendPropertyChanging();
					this._MaDT = value;
					this.SendPropertyChanged("MaDT");
					this.OnMaDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anh", DbType="Char(100)")]
		public string Anh
		{
			get
			{
				return this._Anh;
			}
			set
			{
				if ((this._Anh != value))
				{
					this.OnAnhChanging(value);
					this.SendPropertyChanging();
					this._Anh = value;
					this.SendPropertyChanged("Anh");
					this.OnAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tLoaiSP_tDanhMucSP", Storage="_tLoaiSP", ThisKey="MaLoai", OtherKey="MaLoai", IsForeignKey=true)]
		public tLoaiSP tLoaiSP
		{
			get
			{
				return this._tLoaiSP.Entity;
			}
			set
			{
				tLoaiSP previousValue = this._tLoaiSP.Entity;
				if (((previousValue != value) 
							|| (this._tLoaiSP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tLoaiSP.Entity = null;
						previousValue.tDanhMucSPs.Remove(this);
					}
					this._tLoaiSP.Entity = value;
					if ((value != null))
					{
						value.tDanhMucSPs.Add(this);
						this._MaLoai = value.MaLoai;
					}
					else
					{
						this._MaLoai = default(string);
					}
					this.SendPropertyChanged("tLoaiSP");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
