//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDocGia
    {
        public string MaDG { get; set; }
        public string HoDem { get; set; }
        public string TenDG { get; set; }
        public string SoCMND { get; set; }
        public string MaDonVi { get; set; }
        public Nullable<System.DateTime> Ngaysinh { get; set; }
        public string MaDT { get; set; }
        public string DiaChi { get; set; }
        public string Anh { get; set; }
    
        public virtual tDoiTuong tDoiTuong { get; set; }
        public virtual tDonVi tDonVi { get; set; }
    }
}
