//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sach.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ThuVienDB : DbContext
    {
        public ThuVienDB()
            : base("name=ThuVienDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tBanSaoSach> tBanSaoSaches { get; set; }
        public virtual DbSet<tDocGia> tDocGias { get; set; }
        public virtual DbSet<tDoiTuong> tDoiTuongs { get; set; }
        public virtual DbSet<tDonVi> tDonVis { get; set; }
        public virtual DbSet<tLoaiSach> tLoaiSaches { get; set; }
        public virtual DbSet<tMuonTra> tMuonTras { get; set; }
        public virtual DbSet<tNgonNgu> tNgonNgus { get; set; }
        public virtual DbSet<tNhaXB> tNhaXBs { get; set; }
        public virtual DbSet<tSach> tSaches { get; set; }
    }
}
