//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMuonTra
    {
        public string MaThe { get; set; }
        public string MaBanSao { get; set; }
        public Nullable<double> DatCoc { get; set; }
        public Nullable<System.DateTime> NgayMuon { get; set; }
        public Nullable<System.DateTime> NgayPhaiTra { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public string TinhTrangSach { get; set; }
        public Nullable<double> Phat { get; set; }
    
        public virtual tBanSaoSach tBanSaoSach { get; set; }
    }
}
